default: &default
  adapter: mysql2
  encoding: utf8
  database: sf_lunch
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default